### PR TITLE
add simple hello world python

### PR DESCRIPTION
**Pull request by aecuto**

### CODE REVIEW

**Comment by Rohithv07** [comment]
Hi @aecuto , could you please resolve the conflict in contributors.md file and commit it again.
Thanks

**Comment by aecuto** [comment]
> Hi @aecuto , could you please resolve the conflict in contributors.md file and commit it again. Thanks

done

**Comment by aecuto** [comment]
done @Rohithv07

**Review by Rohithv07 — APPROVED** [review]
Approved

**Pull request merged**
